const item = [
    {
        name:"omax",
        brand:"max",
        price:333,
        category:"mobile"
    },{
        name:"micromax2",
        brand:"max",
        price:333,
        category:"mobile"
    },{
        name:"micromax3",
        brand:"max",
        price:333,
        category:"mobile"
    },{
        name:"mi",
        brand:"max",
        price:333,
        category:"mobile"
    },
    {
        name:"vivo",
        brand:"max",
        price:333,
        category:"mobile"
    },
    {
        name:"vivo3",
        brand:"max",
        price:333,
        category:"mobile"
    }
]

module.exports=item